import * as NodeChildProcess from "node:child_process";
import * as NodeFS from "node:fs";
import * as NodeModule from "node:module";
import * as NodePath from "node:path";
import { ENVIRONMENT_LUCIDE_ICON_IDS } from "@t3tools/contracts";

const GENERATED_MODULE_PATH = NodePath.resolve(
  import.meta.dirname,
  "../src/components/environmentLucideIcons.generated.ts",
);

// Path data comes from the same lucide-react build web draws, resolved from
// the web workspace so both clients stay on one icon version.
const webRequire = NodeModule.createRequire(
  NodePath.resolve(import.meta.dirname, "../../web/package.json"),
);
const lucideRoot = NodePath.dirname(webRequire.resolve("lucide-react/package.json"));
const lucideVersion = (
  JSON.parse(NodeFS.readFileSync(NodePath.join(lucideRoot, "package.json"), "utf8")) as {
    version: string;
  }
).version;

type IconNode = ReadonlyArray<readonly [string, Readonly<Record<string, string>>]>;

/**
 * Reads the `__iconNode` array out of one lucide-react icon module. The
 * module is plain ESM with a single array literal, parsed as JSON after
 * quoting its keys, so nothing is executed.
 */
function readIconNode(id: string): IconNode {
  const source = NodeFS.readFileSync(
    NodePath.join(lucideRoot, "dist/esm/icons", `${id}.js`),
    "utf8",
  );
  const literal = /const __iconNode = (\[[\s\S]*?\]);\n/u.exec(source)?.[1];
  if (literal === undefined) throw new Error(`lucide-react icon ${id} has no __iconNode literal.`);
  const parsed: unknown = JSON.parse(literal.replaceAll(/(\w+): /gu, '"$1": '));
  if (!Array.isArray(parsed)) throw new Error(`lucide-react icon ${id} did not parse to a list.`);
  return parsed.map((entry: unknown): readonly [string, Readonly<Record<string, string>>] => {
    if (!Array.isArray(entry) || typeof entry[0] !== "string" || typeof entry[1] !== "object") {
      throw new Error(`lucide-react icon ${id} has an unexpected node.`);
    }
    // React needs the key only to reconcile a list; mobile builds a static tree.
    const { key: _key, ...attributes } = entry[1] as Record<string, string>;
    return [entry[0], attributes];
  });
}

/**
 * The module text, passed through the repository formatter so the committed
 * file matches what the pre-commit hook would write and the freshness test
 * compares like with like.
 */
export function renderEnvironmentLucideIconsModule(): string {
  const entries = ENVIRONMENT_LUCIDE_ICON_IDS.map(
    (id) => `  "${id}": ${JSON.stringify(readIconNode(id))},`,
  );
  const raw = [
    "// Generated by scripts/generate-environment-lucide-icons.mts. Do not edit.",
    `// Source: lucide-react ${lucideVersion}, ids from ENVIRONMENT_LUCIDE_ICON_IDS in contracts.`,
    'import type { EnvironmentLucideIconId } from "@t3tools/contracts";',
    "",
    "export type LucideIconNode = ReadonlyArray<",
    "  readonly [element: string, attributes: Readonly<Record<string, string>>]",
    ">;",
    "",
    "export const ENVIRONMENT_LUCIDE_ICON_NODES: Record<EnvironmentLucideIconId, LucideIconNode> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
  // The `vp` bin is a shell shim, so it runs through the shell, not node.
  const formatted = NodeChildProcess.spawnSync(
    NodePath.resolve(import.meta.dirname, "../../../node_modules/.bin/vp"),
    ["fmt", `--stdin-filepath=${GENERATED_MODULE_PATH}`],
    { input: raw, encoding: "utf8", maxBuffer: 16 * 1024 * 1024 },
  );
  if (formatted.status !== 0) {
    throw new Error(`vp fmt failed while formatting the generated module: ${formatted.stderr}`);
  }
  return formatted.stdout;
}

if (import.meta.main) {
  const contents = renderEnvironmentLucideIconsModule();
  if (process.argv.includes("--check")) {
    const current = NodeFS.existsSync(GENERATED_MODULE_PATH)
      ? NodeFS.readFileSync(GENERATED_MODULE_PATH, "utf8")
      : null;
    if (current !== contents) {
      console.error(
        `${NodePath.relative(process.cwd(), GENERATED_MODULE_PATH)} is stale. Run vp run --filter @t3tools/mobile generate:lucide-icons.`,
      );
      process.exitCode = 1;
    }
  } else {
    NodeFS.writeFileSync(GENERATED_MODULE_PATH, contents);
  }
}
